Repository freemed-it/techblog, pull requests merged in 2024-08, with the labels that each got.

#30 refactor: 코드 리팩토링
  posts/tech/homepage-gatsby/index.mdx
  public/header-mobile.png
  public/header-pc.png
  src/app/[category]/[slug]/page.tsx
  src/app/[category]/page.tsx
  src/app/page.tsx
  src/components/post_detail/PostBody.tsx
  src/components/post_detail/PostHeader.tsx
  src/components/post_list/PostList.tsx
  src/config/types.ts
  src/lib/posts.ts
  tailwind.config.ts
Labels: 🛠 refactor

#33 docs: Next.js로 프리메드 기술 블로그를 만들기까지
  posts/tech/homepage-gatsby/index.mdx
  posts/tech/techblog-nextjs/index.mdx
  public/posts/tech/hompage-gatsby/content_01.png
  public/posts/tech/hompage-gatsby/thumbnail_01.png
  public/posts/tech/techblog-nextjs/profile.png
  public/posts/tech/techblog-nextjs/thumbnail_01.png
Labels: 📋 docs

#34 docs: Gatsby를 활용한 프리메드 홈페이지 리뉴얼 개발기
  posts/tech/homepage-gatsby/index.mdx
  public/posts/tech/homepage-gatsby/1.png
  public/posts/tech/homepage-gatsby/2.png
  public/posts/tech/homepage-gatsby/3.png
  public/posts/tech/homepage-gatsby/4.png
  public/posts/tech/homepage-gatsby/profile.png
  public/posts/tech/homepage-gatsby/thumbnail.png
Labels: 📋 docs

#36 release: v1.0.1
  public/og-image.png
Labels: 🌏 deploy
